In [1]:
import numpy as np

In [3]:
a = np.arange(6).reshape((3, 2))

In [4]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
np.reshape(np.ravel(a), (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
np.reshape(a, (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [8]:
np.reshape(np.ravel(a, order='F'), (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [9]:
a = np.array([[1,2,3], [4,5,6]])

In [10]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [11]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [12]:
np.reshape(a, (3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])